// A small, strict SVG parser for the build scripts. It accepts only the subset our sources use
// (elements and attributes, no text) and turns markup into data that React renders without
// dangerouslySetInnerHTML. Anything unexpected is an error, not a silent pass-through.

const forbiddenTags = new Set(['script', 'foreignObject', 'style', 'text']);

/**
 * @typedef {[string, Record<string, string>] | [string, Record<string, string>, unknown[]]} SvgNode
 * @typedef {{ attrs: Record<string, string>, children: SvgNode[] }} ParsedSvg
 */

/**
 * @param {string} markup
 * @returns {ParsedSvg}
 */
export function parseSvg(markup) {
  const source = markup
    .replace(/<\?[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim();
  const tagPattern = /<(\/?)([A-Za-z][\w:-]*)((?:\s+[\w:-]+="[^"]*")*)\s*(\/?)>/g;
  /** @type {{ tag: string, attrs: Record<string, string>, children: SvgNode[] }[]} */
  const stack = [];
  /** @type {ParsedSvg | undefined} */
  let root;
  let cursor = 0;

  for (const match of source.matchAll(tagPattern)) {
    const between = source.slice(cursor, match.index);
    if (between.trim() !== '') throw new Error(`Unexpected text content: "${between.trim()}"`);
    cursor = match.index + match[0].length;

    const [, closing, tag = '', rawAttrs = '', selfClosing] = match;
    if (forbiddenTags.has(tag)) throw new Error(`Forbidden element <${tag}>`);

    if (closing) {
      const open = stack.pop();
      if (open?.tag !== tag) throw new Error(`Unexpected closing tag </${tag}>`);
      if (stack.length === 0) root = { attrs: open.attrs, children: open.children };
      else attach(stack, toNode(open));
      continue;
    }

    const attrs = parseAttributes(rawAttrs);
    if (selfClosing) {
      if (stack.length === 0) throw new Error(`Root <${tag}> cannot be self-closing`);
      attach(stack, [tag, attrs]);
    } else {
      stack.push({ tag, attrs, children: [] });
    }
  }

  const rest = source.slice(cursor);
  if (rest.trim() !== '') throw new Error(`Unexpected text content: "${rest.trim()}"`);
  if (stack.length > 0 || !root) throw new Error('Missing closing tag');
  return root;
}

/** @param {string} raw */
function parseAttributes(raw) {
  /** @type {Record<string, string>} */
  const attrs = {};
  for (const [, name = '', value = ''] of raw.matchAll(/([\w:-]+)="([^"]*)"/g)) {
    if (/^on/i.test(name)) throw new Error(`Forbidden attribute ${name}`);
    attrs[name] = value;
  }
  return attrs;
}

/** @param {{ tag: string, attrs: Record<string, string>, children: SvgNode[] }} element @returns {SvgNode} */
function toNode(element) {
  return element.children.length > 0
    ? [element.tag, element.attrs, element.children]
    : [element.tag, element.attrs];
}

/** @param {{ children: SvgNode[] }[]} stack @param {SvgNode} node */
function attach(stack, node) {
  const parent = stack.at(-1);
  if (!parent) throw new Error('Element outside the root');
  parent.children.push(node);
}

/**
 * Renders a generated TypeScript module that maps names to SVG node lists.
 * @param {string} exportName
 * @param {string} description
 * @param {Record<string, SvgNode[]>} entries
 */
export function renderSvgModule(exportName, description, entries) {
  const body = Object.entries(entries)
    .map(([name, nodes]) => `  ${formatKey(name)}: ${formatNodes(nodes)},`)
    .join('\n');
  return [
    `// Generated by packages/atlas/scripts. ${description} Do not edit.`,
    `import type { SvgNode } from './SvgNodes';`,
    '',
    `export const ${exportName} = {`,
    body,
    '} as const satisfies Record<string, readonly SvgNode[]>;',
    '',
  ].join('\n');
}

/** @param {string} key */
function formatKey(key) {
  return /^[A-Za-z_]\w*$/.test(key) ? key : `'${key}'`;
}

/** @param {SvgNode[]} nodes @returns {string} */
function formatNodes(nodes) {
  return `[${nodes.map(formatNode).join(', ')}]`;
}

/** @param {SvgNode} node @returns {string} */
function formatNode(node) {
  const [tag, attrs, children] = node;
  const attrList = Object.entries(attrs)
    .map(([name, value]) => `${formatKey(name)}: '${value.replaceAll("'", "\\'")}'`)
    .join(', ');
  const parts = [`'${tag}'`, attrList ? `{ ${attrList} }` : '{}'];
  if (children) parts.push(formatNodes(/** @type {SvgNode[]} */ (children)));
  return `[${parts.join(', ')}]`;
}
