// A small, strict SVG parser for the build scripts. It accepts only the subset our sources use
// (elements and attributes, no text) and turns markup into data that React renders without
// dangerouslySetInnerHTML. Anything unexpected is an error, not a silent pass-through.

const forbiddenTags = new Set(['script', 'foreignObject', 'style', 'text']);

/**
 * @typedef {[string, Record<string, string>] | [string, Record<string, string>, unknown[]]} SvgNode
 * @typedef {{ attrs: Record<string, string>, children: SvgNode[] }} ParsedSvg
 */

/**
 * Linear scanner: no backtracking regular expressions, no sanitizing by substitution.
 * @param {string} markup
 * @returns {ParsedSvg}
 */
export function parseSvg(markup) {
  /** @type {{ tag: string, attrs: Record<string, string>, children: SvgNode[] }[]} */
  const stack = [];
  /** @type {ParsedSvg | undefined} */
  let root;
  let index = 0;

  const isSpace = (/** @type {string | undefined} */ char) =>
    char === ' ' || char === '\n' || char === '\t' || char === '\r';
  const isNameChar = (/** @type {string | undefined} */ char) =>
    char !== undefined && /^[\w:-]$/.test(char);
  const skipSpaces = () => {
    while (isSpace(markup[index])) index += 1;
  };
  const readName = () => {
    const start = index;
    while (isNameChar(markup[index])) index += 1;
    if (index === start) throw new Error(`Expected a name at position ${index}`);
    return markup.slice(start, index);
  };
  const skipPast = (/** @type {string} */ terminator) => {
    const end = markup.indexOf(terminator, index);
    if (end === -1) throw new Error(`Unterminated markup at position ${index}`);
    index = end + terminator.length;
  };

  while (index < markup.length) {
    skipSpaces();
    if (index >= markup.length) break;
    if (markup[index] !== '<') {
      throw new Error(`Unexpected text content at position ${index}`);
    }
    if (markup.startsWith('<!--', index)) {
      skipPast('-->');
      continue;
    }
    if (markup.startsWith('<?', index)) {
      skipPast('?>');
      continue;
    }

    if (markup.startsWith('</', index)) {
      index += 2;
      const tag = readName();
      skipSpaces();
      if (markup[index] !== '>') throw new Error(`Malformed closing tag </${tag}>`);
      index += 1;
      const open = stack.pop();
      if (open?.tag !== tag) throw new Error(`Unexpected closing tag </${tag}>`);
      if (stack.length === 0) root = { attrs: open.attrs, children: open.children };
      else attach(stack, toNode(open));
      continue;
    }

    index += 1;
    const tag = readName();
    if (forbiddenTags.has(tag)) throw new Error(`Forbidden element <${tag}>`);
    /** @type {Record<string, string>} */
    const attrs = {};
    let selfClosing = false;
    for (;;) {
      skipSpaces();
      if (markup.startsWith('/>', index)) {
        selfClosing = true;
        index += 2;
        break;
      }
      if (markup[index] === '>') {
        index += 1;
        break;
      }
      const name = readName();
      if (/^on/i.test(name)) throw new Error(`Forbidden attribute ${name}`);
      if (!markup.startsWith('="', index))
        throw new Error(`Attribute ${name} needs a quoted value`);
      index += 2;
      const end = markup.indexOf('"', index);
      if (end === -1) throw new Error(`Unterminated value of ${name}`);
      attrs[name] = markup.slice(index, end);
      index = end + 1;
    }

    if (selfClosing) {
      if (stack.length === 0) throw new Error(`Root <${tag}> cannot be self-closing`);
      attach(stack, [tag, attrs]);
    } else {
      stack.push({ tag, attrs, children: [] });
    }
  }

  if (stack.length > 0 || !root) throw new Error('Missing closing tag');
  return root;
}

/** @param {{ tag: string, attrs: Record<string, string>, children: SvgNode[] }} element @returns {SvgNode} */
function toNode(element) {
  return element.children.length > 0
    ? [element.tag, element.attrs, element.children]
    : [element.tag, element.attrs];
}

/** @param {{ children: SvgNode[] }[]} stack @param {SvgNode} node */
function attach(stack, node) {
  const parent = stack.at(-1);
  if (!parent) throw new Error('Element outside the root');
  parent.children.push(node);
}

/**
 * Renders a generated TypeScript module that maps names to SVG node lists.
 * @param {string} exportName
 * @param {string} description
 * @param {Record<string, SvgNode[]>} entries
 */
export function renderSvgModule(exportName, description, entries) {
  const body = Object.entries(entries)
    .map(([name, nodes]) => `  ${formatKey(name)}: ${formatNodes(nodes)},`)
    .join('\n');
  return [
    `// Generated by packages/atlas/scripts. ${description} Do not edit.`,
    `import type { SvgNode } from './SvgNodes';`,
    '',
    `export const ${exportName} = {`,
    body,
    '} as const satisfies Record<string, readonly SvgNode[]>;',
    '',
  ].join('\n');
}

/** @param {string} key */
function formatKey(key) {
  return /^[A-Za-z_]\w*$/.test(key) ? key : `'${key}'`;
}

/** @param {SvgNode[]} nodes @returns {string} */
function formatNodes(nodes) {
  return `[${nodes.map(formatNode).join(', ')}]`;
}

/** @param {SvgNode} node @returns {string} */
function formatNode(node) {
  const [tag, attrs, children] = node;
  const attrList = Object.entries(attrs)
    .map(([name, value]) => `${formatKey(name)}: '${value.replaceAll("'", "\\'")}'`)
    .join(', ');
  const parts = [`'${tag}'`, attrList ? `{ ${attrList} }` : '{}'];
  if (children) parts.push(formatNodes(/** @type {SvgNode[]} */ (children)));
  return `[${parts.join(', ')}]`;
}
