-- D03 · Reference data of the world, generated from data/map/world.json by
-- data/map/scripts/build_world_seed.py. Do not edit: write a new migration to change the world.
--
-- Rollback: delete from game.regions; delete from game.countries;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

insert into game.countries
  (code, iso2, name_es, name_en, official_name_es, official_name_en, color, is_active)
values
  ('ABW', 'AW', 'Aruba', 'Aruba', null, null, null, false),
  ('AFG', 'AF', 'Afganistán', 'Afghanistan', null, null, null, false),
  ('AGO', 'AO', 'Angola', 'Angola', null, null, null, false),
  ('AIA', 'AI', 'Anguila', 'Anguilla', null, null, null, false),
  ('ALB', 'AL', 'Albania', 'Albania', null, null, null, false),
  ('ALD', 'AX', 'Åland', 'Åland', null, null, null, false),
  ('AND', 'AD', 'Andorra', 'Andorra', null, null, null, false),
  ('ARE', 'AE', 'Emiratos Árabes Unidos', 'United Arab Emirates', null, null, null, false),
  ('ARG', 'AR', 'Argentina', 'Argentina', 'República Argentina', 'Argentine Republic', '#6CACE4', true),
  ('ARM', 'AM', 'Armenia', 'Armenia', null, null, null, false),
  ('ASM', 'AS', 'Samoa Estadounidense', 'American Samoa', null, null, null, false),
  ('ATC', 'AU', 'Islas Ashmore y Cartier', 'Ashmore and Cartier Islands', null, null, null, false),
  ('ATF', 'TF', 'Tierras Australes y Antárticas Francesas', 'French Southern and Antarctic Lands', null, null, null, false),
  ('ATG', 'AG', 'Antigua y Barbuda', 'Antigua and Barbuda', null, null, null, false),
  ('AUS', 'AU', 'Australia', 'Australia', null, null, null, false),
  ('AUT', 'AT', 'Austria', 'Austria', null, null, null, false),
  ('AZE', 'AZ', 'Azerbaiyán', 'Azerbaijan', null, null, null, false),
  ('BDI', 'BI', 'Burundi', 'Burundi', null, null, null, false),
  ('BEL', 'BE', 'Bélgica', 'Belgium', null, null, null, false),
  ('BEN', 'BJ', 'Benín', 'Benin', null, null, null, false),
  ('BFA', 'BF', 'Burkina Faso', 'Burkina Faso', null, null, null, false),
  ('BGD', 'BD', 'Bangladés', 'Bangladesh', null, null, null, false),
  ('BGR', 'BG', 'Bulgaria', 'Bulgaria', null, null, null, false),
  ('BHR', 'BH', 'Baréin', 'Bahrain', null, null, null, false),
  ('BHS', 'BS', 'Bahamas', 'The Bahamas', null, null, null, false),
  ('BIH', 'BA', 'Bosnia y Herzegovina', 'Bosnia and Herzegovina', null, null, null, false),
  ('BLM', 'BL', 'San Bartolomé', 'Saint Barthélemy', null, null, null, false),
  ('BLR', 'BY', 'Bielorrusia', 'Belarus', null, null, null, false),
  ('BLZ', 'BZ', 'Belice', 'Belize', null, null, null, false),
  ('BMU', 'BM', 'Bermudas', 'Bermuda', null, null, null, false),
  ('BOL', 'BO', 'Bolivia', 'Bolivia', null, null, null, false),
  ('BRA', 'BR', 'Brasil', 'Brazil', 'República Federativa del Brasil', 'Federative Republic of Brazil', '#4FA35A', true),
  ('BRB', 'BB', 'Barbados', 'Barbados', null, null, null, false),
  ('BRN', 'BN', 'Brunéi', 'Brunei', null, null, null, false),
  ('BTN', 'BT', 'Bután', 'Bhutan', null, null, null, false),
  ('BWA', 'BW', 'Botsuana', 'Botswana', null, null, null, false),
  ('CAF', 'CF', 'República Centroafricana', 'Central African Republic', null, null, null, false),
  ('CAN', 'CA', 'Canadá', 'Canada', 'Canadá', 'Canada', '#A0703F', true),
  ('CHE', 'CH', 'Suiza', 'Switzerland', null, null, null, false),
  ('CHL', 'CL', 'Chile', 'Chile', 'República de Chile', 'Republic of Chile', '#8E5BB5', true),
  ('CHN', 'CN', 'China', 'People''s Republic of China', null, null, null, false),
  ('CIV', 'CI', 'Costa de Marfil', 'Ivory Coast', null, null, null, false),
  ('CLP', null, 'Isla Clipperton', 'Clipperton Island', null, null, null, false),
  ('CMR', 'CM', 'Camerún', 'Cameroon', null, null, null, false),
  ('COD', 'CD', 'República Democrática del Congo', 'Democratic Republic of the Congo', null, null, null, false),
  ('COG', 'CG', 'República del Congo', 'Republic of the Congo', null, null, null, false),
  ('COK', 'CK', 'Islas Cook', 'Cook Islands', null, null, null, false),
  ('COL', 'CO', 'Colombia', 'Colombia', null, null, null, false),
  ('COM', 'KM', 'Comoras', 'Comoros', null, null, null, false),
  ('CPV', 'CV', 'Cabo Verde', 'Cape Verde', null, null, null, false),
  ('CRI', 'CR', 'Costa Rica', 'Costa Rica', null, null, null, false),
  ('CSI', null, 'Islas del Mar del Coral', 'Coral Sea Islands', null, null, null, false),
  ('CUB', 'CU', 'Cuba', 'Cuba', null, null, null, false),
  ('CUW', 'CW', 'Curazao', 'Curaçao', null, null, null, false),
  ('CYM', 'KY', 'Islas Caimán', 'Cayman Islands', null, null, null, false),
  ('CYN', null, 'República Turca del Norte de Chipre', 'Turkish Republic of Northern Cyprus', null, null, null, false),
  ('CYP', 'CY', 'Chipre', 'Cyprus', null, null, null, false),
  ('CZE', 'CZ', 'República Checa', 'Czech Republic', null, null, null, false),
  ('DEU', 'DE', 'Alemania', 'Germany', 'República Federal de Alemania', 'Federal Republic of Germany', '#D9B737', true),
  ('DJI', 'DJ', 'Yibuti', 'Djibouti', null, null, null, false),
  ('DMA', 'DM', 'Dominica', 'Dominica', null, null, null, false),
  ('DNK', 'DK', 'Dinamarca', 'Denmark', null, null, null, false),
  ('DOM', 'DO', 'República Dominicana', 'Dominican Republic', null, null, null, false),
  ('DZA', 'DZ', 'Argelia', 'Algeria', null, null, null, false),
  ('ECU', 'EC', 'Ecuador', 'Ecuador', null, null, null, false),
  ('EGY', 'EG', 'Egipto', 'Egypt', null, null, null, false),
  ('ERI', 'ER', 'Eritrea', 'Eritrea', null, null, null, false),
  ('ESB', null, 'Dhekelia', 'Dhekelia', null, null, null, false),
  ('ESP', 'ES', 'España', 'Spain', 'Reino de España', 'Kingdom of Spain', '#D0453A', true),
  ('EST', 'EE', 'Estonia', 'Estonia', null, null, null, false),
  ('ETH', 'ET', 'Etiopía', 'Ethiopia', null, null, null, false),
  ('FIN', 'FI', 'Finlandia', 'Finland', null, null, null, false),
  ('FJI', 'FJ', 'Fiyi', 'Fiji', null, null, null, false),
  ('FLK', 'FK', 'Islas Malvinas', 'Falkland Islands', null, null, null, false),
  ('FRA', 'FR', 'Francia', 'France', 'República Francesa', 'French Republic', '#4E79C4', true),
  ('FRO', 'FO', 'Islas Feroe', 'Faroe Islands', null, null, null, false),
  ('FSM', 'FM', 'Estados Federados de Micronesia', 'Federated States of Micronesia', null, null, null, false),
  ('GAB', 'GA', 'Gabón', 'Gabon', null, null, null, false),
  ('GBR', 'GB', 'Reino Unido', 'United Kingdom', 'Reino Unido de Gran Bretaña e Irlanda del Norte', 'United Kingdom of Great Britain and Northern Ireland', '#A8558F', true),
  ('GEO', 'GE', 'Georgia', 'Georgia', null, null, null, false),
  ('GGY', 'GG', 'Guernsey', 'Guernsey', null, null, null, false),
  ('GHA', 'GH', 'Ghana', 'Ghana', null, null, null, false),
  ('GIB', 'GI', 'Gibraltar', 'Gibraltar', null, null, null, false),
  ('GIN', 'GN', 'Guinea', 'Guinea', null, null, null, false),
  ('GMB', 'GM', 'Gambia', 'The Gambia', null, null, null, false),
  ('GNB', 'GW', 'Guinea-Bisáu', 'Guinea-Bissau', null, null, null, false),
  ('GNQ', 'GQ', 'Guinea Ecuatorial', 'Equatorial Guinea', null, null, null, false),
  ('GRC', 'GR', 'Grecia', 'Greece', null, null, null, false),
  ('GRD', 'GD', 'Granada', 'Grenada', null, null, null, false),
  ('GRL', 'GL', 'Groenlandia', 'Greenland', null, null, null, false),
  ('GTM', 'GT', 'Guatemala', 'Guatemala', null, null, null, false),
  ('GUM', 'GU', 'Guam', 'Guam', null, null, null, false),
  ('GUY', 'GY', 'Guyana', 'Guyana', null, null, null, false),
  ('HKG', 'HK', 'Hong Kong', 'Hong Kong', null, null, null, false),
  ('HMD', 'HM', 'Islas Heard y McDonald', 'Heard Island and McDonald Islands', null, null, null, false),
  ('HND', 'HN', 'Honduras', 'Honduras', null, null, null, false),
  ('HRV', 'HR', 'Croacia', 'Croatia', null, null, null, false),
  ('HTI', 'HT', 'Haití', 'Haiti', null, null, null, false),
  ('HUN', 'HU', 'Hungría', 'Hungary', null, null, null, false),
  ('IDN', 'ID', 'Indonesia', 'Indonesia', null, null, null, false),
  ('IMN', 'IM', 'Isla de Man', 'Isle of Man', null, null, null, false),
  ('IND', 'IN', 'India', 'India', null, null, null, false),
  ('IOA', 'AU', 'Territorios Australianos del Océano Índico', 'Australian Indian Ocean Territories', null, null, null, false),
  ('IOT', 'IO', 'Territorio Británico del Océano Índico', 'British Indian Ocean Territory', null, null, null, false),
  ('IRL', 'IE', 'Irlanda', 'Ireland', null, null, null, false),
  ('IRN', 'IR', 'Irán', 'Iran', null, null, null, false),
  ('IRQ', 'IQ', 'Irak', 'Iraq', null, null, null, false),
  ('ISL', 'IS', 'Islandia', 'Iceland', null, null, null, false),
  ('ISR', 'IL', 'Israel', 'Israel', null, null, null, false),
  ('ITA', 'IT', 'Italia', 'Italy', 'República Italiana', 'Italian Republic', '#5BB3A5', true),
  ('JAM', 'JM', 'Jamaica', 'Jamaica', null, null, null, false),
  ('JEY', 'JE', 'Jersey', 'Jersey', null, null, null, false),
  ('JOR', 'JO', 'Jordania', 'Jordan', null, null, null, false),
  ('JPN', 'JP', 'Japón', 'Japan', null, null, null, false),
  ('KAB', null, 'Baikonur', 'Baikonur', null, null, null, false),
  ('KAS', null, 'Glaciar de Siachen', 'Siachen Glacier', null, null, null, false),
  ('KAZ', 'KZ', 'Kazajistán', 'Kazakhstan', null, null, null, false),
  ('KEN', 'KE', 'Kenia', 'Kenya', null, null, null, false),
  ('KGZ', 'KG', 'Kirguistán', 'Kyrgyzstan', null, null, null, false),
  ('KHM', 'KH', 'Camboya', 'Cambodia', null, null, null, false),
  ('KIR', 'KI', 'Kiribati', 'Kiribati', null, null, null, false),
  ('KNA', 'KN', 'San Cristóbal y Nieves', 'Saint Kitts and Nevis', null, null, null, false),
  ('KOR', 'KR', 'Corea del Sur', 'South Korea', null, null, null, false),
  ('KOS', 'XK', 'Kosovo', 'Kosovo', null, null, null, false),
  ('KWT', 'KW', 'Kuwait', 'Kuwait', null, null, null, false),
  ('LAO', 'LA', 'Laos', 'Laos', null, null, null, false),
  ('LBN', 'LB', 'Líbano', 'Lebanon', null, null, null, false),
  ('LBR', 'LR', 'Liberia', 'Liberia', null, null, null, false),
  ('LBY', 'LY', 'Libia', 'Libya', null, null, null, false),
  ('LCA', 'LC', 'Santa Lucía', 'Saint Lucia', null, null, null, false),
  ('LIE', 'LI', 'Liechtenstein', 'Liechtenstein', null, null, null, false),
  ('LKA', 'LK', 'Sri Lanka', 'Sri Lanka', null, null, null, false),
  ('LSO', 'LS', 'Lesoto', 'Lesotho', null, null, null, false),
  ('LTU', 'LT', 'Lituania', 'Lithuania', null, null, null, false),
  ('LUX', 'LU', 'Luxemburgo', 'Luxembourg', null, null, null, false),
  ('LVA', 'LV', 'Letonia', 'Latvia', null, null, null, false),
  ('MAC', 'MO', 'Macao', 'Macau', null, null, null, false),
  ('MAF', 'MF', 'San Martín', 'Saint Martin', null, null, null, false),
  ('MAR', 'MA', 'Marruecos', 'Morocco', null, null, null, false),
  ('MCO', 'MC', 'Mónaco', 'Monaco', null, null, null, false),
  ('MDA', 'MD', 'Moldavia', 'Moldova', null, null, null, false),
  ('MDG', 'MG', 'Madagascar', 'Madagascar', null, null, null, false),
  ('MDV', 'MV', 'Maldivas', 'Maldives', null, null, null, false),
  ('MEX', 'MX', 'México', 'Mexico', 'Estados Unidos Mexicanos', 'United Mexican States', '#2E8B7A', true),
  ('MHL', 'MH', 'Islas Marshall', 'Marshall Islands', null, null, null, false),
  ('MKD', 'MK', 'Macedonia del Norte', 'North Macedonia', null, null, null, false),
  ('MLI', 'ML', 'Malí', 'Mali', null, null, null, false),
  ('MLT', 'MT', 'Malta', 'Malta', null, null, null, false),
  ('MMR', 'MM', 'Birmania', 'Myanmar', null, null, null, false),
  ('MNE', 'ME', 'Montenegro', 'Montenegro', null, null, null, false),
  ('MNG', 'MN', 'Mongolia', 'Mongolia', null, null, null, false),
  ('MNP', 'MP', 'Islas Marianas del Norte', 'Northern Mariana Islands', null, null, null, false),
  ('MOZ', 'MZ', 'Mozambique', 'Mozambique', null, null, null, false),
  ('MRT', 'MR', 'Mauritania', 'Mauritania', null, null, null, false),
  ('MSR', 'MS', 'Montserrat', 'Montserrat', null, null, null, false),
  ('MUS', 'MU', 'Mauricio', 'Mauritius', null, null, null, false),
  ('MWI', 'MW', 'Malaui', 'Malawi', null, null, null, false),
  ('MYS', 'MY', 'Malasia', 'Malaysia', null, null, null, false),
  ('NAM', 'NA', 'Namibia', 'Namibia', null, null, null, false),
  ('NCL', 'NC', 'Nueva Caledonia', 'New Caledonia', null, null, null, false),
  ('NER', 'NE', 'Níger', 'Niger', null, null, null, false),
  ('NFK', 'NF', 'Isla Norfolk', 'Norfolk Island', null, null, null, false),
  ('NGA', 'NG', 'Nigeria', 'Nigeria', null, null, null, false),
  ('NIC', 'NI', 'Nicaragua', 'Nicaragua', null, null, null, false),
  ('NIU', 'NU', 'Niue', 'Niue', null, null, null, false),
  ('NLD', 'NL', 'Países Bajos', 'Netherlands', null, null, null, false),
  ('NOR', 'NO', 'Noruega', 'Norway', null, null, null, false),
  ('NPL', 'NP', 'Nepal', 'Nepal', null, null, null, false),
  ('NRU', 'NR', 'Nauru', 'Nauru', null, null, null, false),
  ('NZL', 'NZ', 'Nueva Zelanda', 'New Zealand', null, null, null, false),
  ('OMN', 'OM', 'Omán', 'Oman', null, null, null, false),
  ('PAK', 'PK', 'Pakistán', 'Pakistan', null, null, null, false),
  ('PAN', 'PA', 'Panamá', 'Panama', null, null, null, false),
  ('PCN', 'PN', 'Islas Pitcairn', 'Pitcairn Islands', null, null, null, false),
  ('PER', 'PE', 'Perú', 'Peru', null, null, null, false),
  ('PGA', null, 'Islas Spratly', 'Spratly Islands', null, null, null, false),
  ('PHL', 'PH', 'Filipinas', 'Philippines', null, null, null, false),
  ('PLW', 'PW', 'Palaos', 'Palau', null, null, null, false),
  ('PNG', 'PG', 'Papúa Nueva Guinea', 'Papua New Guinea', null, null, null, false),
  ('POL', 'PL', 'Polonia', 'Poland', null, null, null, false),
  ('PRI', 'PR', 'Puerto Rico', 'Puerto Rico', null, null, null, false),
  ('PRK', 'KP', 'Corea del Norte', 'North Korea', null, null, null, false),
  ('PRT', 'PT', 'Portugal', 'Portugal', 'República Portuguesa', 'Portuguese Republic', '#2F6E45', true),
  ('PRY', 'PY', 'Paraguay', 'Paraguay', 'República del Paraguay', 'Republic of Paraguay', '#E0A33A', true),
  ('PSX', 'PS', 'Palestina', 'Palestine', null, null, null, false),
  ('PYF', 'PF', 'Polinesia Francesa', 'French Polynesia', null, null, null, false),
  ('QAT', 'QA', 'Catar', 'Qatar', null, null, null, false),
  ('ROU', 'RO', 'Rumania', 'Romania', null, null, null, false),
  ('RUS', 'RU', 'Rusia', 'Russia', null, null, null, false),
  ('RWA', 'RW', 'Ruanda', 'Rwanda', null, null, null, false),
  ('SAH', 'EH', 'Sahara Occidental', 'Western Sahara', null, null, null, false),
  ('SAU', 'SA', 'Arabia Saudita', 'Saudi Arabia', null, null, null, false),
  ('SDN', 'SD', 'Sudán', 'Sudan', null, null, null, false),
  ('SDS', 'SS', 'Sudán del Sur', 'South Sudan', null, null, null, false),
  ('SEN', 'SN', 'Senegal', 'Senegal', null, null, null, false),
  ('SGP', 'SG', 'Singapur', 'Singapore', null, null, null, false),
  ('SGS', 'GS', 'Islas Georgias del Sur y Sandwich del Sur', 'South Georgia and the South Sandwich Islands', null, null, null, false),
  ('SHN', 'SH', 'Isla Santa Elena', 'Saint Helena', null, null, null, false),
  ('SLB', 'SB', 'Islas Salomón', 'Solomon Islands', null, null, null, false),
  ('SLE', 'SL', 'Sierra Leona', 'Sierra Leone', null, null, null, false),
  ('SLV', 'SV', 'El Salvador', 'El Salvador', null, null, null, false),
  ('SMR', 'SM', 'San Marino', 'San Marino', null, null, null, false),
  ('SOL', null, 'Somalilandia', 'Somaliland', null, null, null, false),
  ('SOM', 'SO', 'Somalia', 'Somalia', null, null, null, false),
  ('SPM', 'PM', 'San Pedro y Miquelón', 'Saint Pierre and Miquelon', null, null, null, false),
  ('SRB', 'RS', 'Serbia', 'Serbia', null, null, null, false),
  ('STP', 'ST', 'Santo Tomé y Príncipe', 'São Tomé and Príncipe', null, null, null, false),
  ('SUR', 'SR', 'Surinam', 'Suriname', null, null, null, false),
  ('SVK', 'SK', 'Eslovaquia', 'Slovakia', null, null, null, false),
  ('SVN', 'SI', 'Eslovenia', 'Slovenia', null, null, null, false),
  ('SWE', 'SE', 'Suecia', 'Sweden', null, null, null, false),
  ('SWZ', 'SZ', 'Suazilandia', 'Eswatini', null, null, null, false),
  ('SXM', 'SX', 'San Martín', 'Sint Maarten', null, null, null, false),
  ('SYC', 'SC', 'Seychelles', 'Seychelles', null, null, null, false),
  ('SYR', 'SY', 'Siria', 'Syria', null, null, null, false),
  ('TCA', 'TC', 'Islas Turcas y Caicos', 'Turks and Caicos Islands', null, null, null, false),
  ('TCD', 'TD', 'Chad', 'Chad', null, null, null, false),
  ('TGO', 'TG', 'Togo', 'Togo', null, null, null, false),
  ('THA', 'TH', 'Tailandia', 'Thailand', null, null, null, false),
  ('TJK', 'TJ', 'Tayikistán', 'Tajikistan', null, null, null, false),
  ('TKM', 'TM', 'Turkmenistán', 'Turkmenistan', null, null, null, false),
  ('TLS', 'TL', 'Timor Oriental', 'East Timor', null, null, null, false),
  ('TON', 'TO', 'Tonga', 'Tonga', null, null, null, false),
  ('TTO', 'TT', 'Trinidad y Tobago', 'Trinidad and Tobago', null, null, null, false),
  ('TUN', 'TN', 'Túnez', 'Tunisia', null, null, null, false),
  ('TUR', 'TR', 'Turquía', 'Turkey', null, null, null, false),
  ('TUV', 'TV', 'Tuvalu', 'Tuvalu', null, null, null, false),
  ('TWN', 'TW', 'República de China', 'Taiwan', null, null, null, false),
  ('TZA', 'TZ', 'Tanzania', 'Tanzania', null, null, null, false),
  ('UGA', 'UG', 'Uganda', 'Uganda', null, null, null, false),
  ('UKR', 'UA', 'Ucrania', 'Ukraine', null, null, null, false),
  ('UMI', 'UM', 'Islas Ultramarinas de Estados Unidos', 'U.S. Minor Outlying Islands', null, null, null, false),
  ('URY', 'UY', 'Uruguay', 'Uruguay', null, null, null, false),
  ('USA', 'US', 'Estados Unidos', 'United States', 'Estados Unidos de América', 'United States of America', '#3C5A9A', true),
  ('USG', null, 'Base naval de Guantánamo', 'Guantanamo Bay Naval Base', null, null, null, false),
  ('UZB', 'UZ', 'Uzbekistán', 'Uzbekistan', null, null, null, false),
  ('VAT', 'VA', 'Ciudad del Vaticano', 'Vatican City', null, null, null, false),
  ('VCT', 'VC', 'San Vicente y las Granadinas', 'Saint Vincent and the Grenadines', null, null, null, false),
  ('VEN', 'VE', 'Venezuela', 'Venezuela', null, null, null, false),
  ('VGB', 'VG', 'Islas Vírgenes Británicas', 'British Virgin Islands', null, null, null, false),
  ('VIR', 'VI', 'Islas Vírgenes de los Estados Unidos', 'United States Virgin Islands', null, null, null, false),
  ('VNM', 'VN', 'Vietnam', 'Vietnam', null, null, null, false),
  ('VUT', 'VU', 'Vanuatu', 'Vanuatu', null, null, null, false),
  ('WLF', 'WF', 'Wallis y Futuna', 'Wallis and Futuna', null, null, null, false),
  ('WSB', null, 'Acrotiri', 'Akrotiri', null, null, null, false),
  ('WSM', 'WS', 'Samoa', 'Samoa', null, null, null, false),
  ('YEM', 'YE', 'Yemen', 'Yemen', null, null, null, false),
  ('ZAF', 'ZA', 'Sudáfrica', 'South Africa', null, null, null, false),
  ('ZMB', 'ZM', 'Zambia', 'Zambia', null, null, null, false),
  ('ZWE', 'ZW', 'Zimbabue', 'Zimbabwe', null, null, null, false);

insert into game.regions (code, home_country_code, owner_country_code, name, provinces)
values
  ('ARG-01', 'ARG', 'ARG', 'Buenos Aires', array['Buenos Aires']::text[]),
  ('ARG-02', 'ARG', 'ARG', 'Córdoba y el Litoral', array['Córdoba', 'Entre Ríos', 'Santa Fe']::text[]),
  ('ARG-03', 'ARG', 'ARG', 'Norte Andino', array['Catamarca', 'Jujuy', 'Salta', 'Santiago del Estero', 'Tucumán']::text[]),
  ('ARG-04', 'ARG', 'ARG', 'Gran Chaco y Misiones', array['Chaco', 'Corrientes', 'Formosa', 'Misiones']::text[]),
  ('ARG-05', 'ARG', 'ARG', 'Cuyo', array['La Rioja', 'Mendoza', 'San Juan', 'San Luis']::text[]),
  ('ARG-06', 'ARG', 'ARG', 'Patagonia', array['Chubut', 'La Pampa', 'Neuquén', 'Río Negro', 'Santa Cruz', 'Tierra del Fuego']::text[]),
  ('BRA-01', 'BRA', 'BRA', 'Alto Amazonas', array['Amazonas', 'Roraima']::text[]),
  ('BRA-02', 'BRA', 'BRA', 'Grão-Pará', array['Amapá', 'Pará', 'Tocantins']::text[]),
  ('BRA-03', 'BRA', 'BRA', 'Acre y Rondônia', array['Estado de Acre', 'Rondônia']::text[]),
  ('BRA-04', 'BRA', 'BRA', 'Meio-Norte', array['Maranhão', 'Piauí']::text[]),
  ('BRA-05', 'BRA', 'BRA', 'Ceará y Borborema', array['Ceará', 'Paraíba', 'Río Grande del Norte']::text[]),
  ('BRA-06', 'BRA', 'BRA', 'Pernambuco y São Francisco', array['Alagoas', 'Pernambuco', 'Sergipe']::text[]),
  ('BRA-07', 'BRA', 'BRA', 'Bahía', array['Bahía']::text[]),
  ('BRA-08', 'BRA', 'BRA', 'Planalto Central y Pantanal', array['Federal', 'Goiás', 'Mato Grosso', 'Mato Grosso do Sul']::text[]),
  ('BRA-09', 'BRA', 'BRA', 'Minas Gerais', array['Minas Gerais']::text[]),
  ('BRA-10', 'BRA', 'BRA', 'São Paulo', array['Estado de São Paulo']::text[]),
  ('BRA-11', 'BRA', 'BRA', 'Rio de Janeiro y Espírito Santo', array['Espírito Santo', 'Estado de Río de Janeiro']::text[]),
  ('BRA-12', 'BRA', 'BRA', 'Pampa Gaúcha y Paraná', array['Paraná', 'Río Grande del Sur', 'Santa Catarina']::text[]),
  ('CAN-01', 'CAN', 'CAN', 'Provincias Atlánticas', array['Isla del Príncipe Eduardo', 'Nueva Escocia', 'Nuevo Brunswick', 'Terranova y Labrador']::text[]),
  ('CAN-02', 'CAN', 'CAN', 'Quebec', array['Quebec']::text[]),
  ('CAN-03', 'CAN', 'CAN', 'Ontario', array['Ontario']::text[]),
  ('CAN-04', 'CAN', 'CAN', 'Praderas', array['Alberta', 'Manitoba', 'Saskatchewan']::text[]),
  ('CAN-05', 'CAN', 'CAN', 'Columbia Británica', array['Columbia Británica']::text[]),
  ('CAN-06', 'CAN', 'CAN', 'Yukón y el Ártico', array['Nunavut', 'Territorios del Noroeste', 'Yukón']::text[]),
  ('CHL-01', 'CHL', 'CHL', 'Norte Grande', array['Antofagasta', 'Arica y Parinacota', 'Tarapacá']::text[]),
  ('CHL-02', 'CHL', 'CHL', 'Norte Chico', array['Atacama', 'Coquimbo']::text[]),
  ('CHL-03', 'CHL', 'CHL', 'Valle Central', array['Maule', 'O''Higgins', 'Santiago', 'Valparaíso']::text[]),
  ('CHL-04', 'CHL', 'CHL', 'Biobío y Los Lagos', array['Biobío', 'La Araucanía', 'Los Lagos', 'Los Ríos', 'Ñuble']::text[]),
  ('CHL-05', 'CHL', 'CHL', 'Patagonia Chilena', array['Aysén del General Carlos Ibáñez del Campo', 'Magallanes y de la Antártica Chilena']::text[]),
  ('DEU-01', 'DEU', 'DEU', 'Mar del Norte y Báltico', array['Baja Sajonia', 'Bremen', 'Hamburgo', 'Mecklemburgo-Pomerania Occidental', 'Schleswig-Holstein']::text[]),
  ('DEU-02', 'DEU', 'DEU', 'Renania del Norte-Westfalia', array['Renania del Norte-Westfalia']::text[]),
  ('DEU-03', 'DEU', 'DEU', 'Valle del Rin', array['Baden-Wurtemberg', 'Hesse', 'Renania-Palatinado', 'Sarre']::text[]),
  ('DEU-04', 'DEU', 'DEU', 'Berlín y Sajonia', array['Berlín', 'Brandeburgo', 'Sajonia', 'Sajonia-Anhalt', 'Turingia']::text[]),
  ('DEU-05', 'DEU', 'DEU', 'Baviera', array['Baviera']::text[]),
  ('ESP-01', 'ESP', 'ESP', 'Galicia y el Cantábrico', array['Asturias', 'Cantabria', 'La Coruña', 'Lugo', 'Orense', 'Pontevedra']::text[]),
  ('ESP-02', 'ESP', 'ESP', 'País Vasco y el Ebro', array['Guipúzcoa', 'Huesca', 'La Rioja', 'Navarra', 'Teruel', 'Vizcaya', 'Zaragoza', 'Álava']::text[]),
  ('ESP-03', 'ESP', 'ESP', 'Madrid', array['Madrid']::text[]),
  ('ESP-04', 'ESP', 'ESP', 'Castillas y Extremadura', array['Albacete', 'Badajoz', 'Burgos', 'Ciudad Real', 'Cuenca', 'Cáceres', 'Guadalajara', 'León', 'Palencia', 'Salamanca', 'Segovia', 'Soria', 'Toledo', 'Valladolid', 'Zamora', 'Ávila']::text[]),
  ('ESP-05', 'ESP', 'ESP', 'Cataluña y Levante', array['Alicante', 'Barcelona', 'Castellón', 'Gerona', 'Islas Baleares', 'Lérida', 'Tarragona', 'Valencia']::text[]),
  ('ESP-06', 'ESP', 'ESP', 'Andalucía y Murcia', array['Almería', 'Ceuta', 'Cádiz', 'Córdoba', 'Granada', 'Huelva', 'Jaén', 'Melilla', 'Murcia', 'Málaga', 'Sevilla']::text[]),
  ('ESP-07', 'ESP', 'ESP', 'Canarias', array['Las Palmas', 'Santa Cruz de Tenerife']::text[]),
  ('FRA-01', 'FRA', 'FRA', 'París y el Canal', array['Aisne', 'Altos del Sena', 'Calvados', 'Essonne', 'Eure', 'Mancha', 'Norte', 'Oise', 'Orne', 'París', 'Paso de Calais', 'Sena Marítimo', 'Sena y Marne', 'Sena-Saint Denis', 'Somme', 'Valle del Marne', 'Valle del Oise', 'Yvelines']::text[]),
  ('FRA-02', 'FRA', 'FRA', 'Bretaña y Loira', array['Cher', 'Côtes-d''Armor', 'Eure y Loir', 'Finisterre', 'Ille y Vilaine', 'Indre', 'Indre y Loira', 'Loir y Cher', 'Loira Atlántico', 'Loiret', 'Maine y Loira', 'Mayenne', 'Morbihan', 'Sarthe', 'Vandea']::text[]),
  ('FRA-03', 'FRA', 'FRA', 'Alsacia y Borgoña', array['Alto Marne', 'Alto Rin', 'Alto Saona', 'Ardenas', 'Aube', 'Bajo Rin', 'Côte-d’Or', 'Doubs', 'Jura', 'Marne', 'Meurthe y Mosela', 'Mosa', 'Mosela', 'Nièvre', 'Saona y Loira', 'Territorio de Belfort', 'Vosgos', 'Yonne']::text[]),
  ('FRA-04', 'FRA', 'FRA', 'Aquitania y Occitania', array['Alto Garona', 'Alto Vienne', 'Altos Pirineos', 'Ariège', 'Aude', 'Aveyron', 'Charente', 'Charente Marítimo', 'Corréze', 'Creuse', 'Deux-Sèvres', 'Dordoña', 'Gard', 'Gers', 'Gironda', 'Hérault', 'Landas', 'Lot', 'Lot y Garona', 'Lozère', 'Pirineos Atlánticos', 'Pirineos Orientales', 'Tarn', 'Tarn y Garona', 'Vienne']::text[]),
  ('FRA-05', 'FRA', 'FRA', 'Ródano y Provenza', array['Ain', 'Allier', 'Alpes Marítimos', 'Alpes de Alta Provenza', 'Alta Córcega', 'Alta Saboya', 'Alto Loira', 'Altos Alpes', 'Ardecha', 'Bocas del Ródano', 'Cantal', 'Córcega del Sur', 'Drôme', 'Isère', 'Loira', 'Puy-de-Dôme', 'Ródano', 'Saboya', 'Var', 'Vaucluse']::text[]),
  ('FRA-06', 'FRA', 'FRA', 'Francia de Ultramar', array['Guadalupe', 'Guayana Francesa', 'Martinica', 'Mayotte', 'Reunión']::text[]),
  ('GBR-01', 'GBR', 'GBR', 'Inglaterra', array['Barking y Dagenham', 'Bath and North East Somerset', 'Bedford', 'Birmingham', 'Blackburn with Darwen', 'Blackpool', 'Bolton', 'Bournemouth', 'Bracknell Forest', 'Bradford', 'Brent', 'Brighton & Hove', 'Brístol', 'Buckinghamshire', 'Calderdale', 'Cambridgeshire', 'Camden', 'Central Bedfordshire', 'Cheshire East', 'Cheshire West and Chester', 'Cornualles', 'Coventry', 'Croydon', 'Cumbria', 'Darlington', 'Derby', 'Derbyshire', 'Devon', 'Dorset', 'Dudley', 'Durham', 'Enfield', 'Essex', 'Gloucestershire', 'Hackney', 'Halton', 'Hammersmith y Fulham', 'Hampshire', 'Haringey', 'Hartlepool', 'Havering', 'Herefordshire', 'Hertfordshire', 'Isla de Wight', 'Islas Sorlingas', 'Kensington y Chelsea', 'Kent', 'Kingston upon Hull', 'Kingston upon Thames', 'Kirklees', 'Knowsley', 'Lancashire', 'Leeds', 'Leicester', 'Leicestershire', 'Lincolnshire', 'Liverpool', 'Luton', 'Medway', 'Merseyside', 'Merton', 'Middlesbrough', 'Municipio de Barnet', 'Municipio de Bexley', 'Municipio de Bromley', 'Municipio de Ealing', 'Municipio de Gateshead', 'Municipio de Greenwich', 'Municipio de Harrow', 'Municipio de Hillingdon', 'Municipio de Hounslow', 'Municipio de Islington', 'Municipio de Lambeth', 'Municipio de Lewisham', 'Municipio de Milton Keynes', 'Municipio de Redbridge', 'Municipio de Stockton-on-Tees', 'Municipio de Sutton', 'Municipio de Wandsworth', 'Municipio metropolitano de Barnsley', 'Municipio metropolitano de Bury', 'Municipio metropolitano de Doncaster', 'Municipio metropolitano de Rotherham', 'Mánchester', 'Newcastle upon Tyne', 'Newham', 'Norfolk', 'North East Lincolnshire', 'North Lincolnshire', 'North Somerset', 'North Tyneside', 'Northamptonshire', 'Northumberland', 'Nottingham', 'Nottinghamshire', 'Oldham', 'Oxfordshire', 'Peterborough', 'Plymouth', 'Poole', 'Portsmouth', 'Reading', 'Redcar and Cleveland', 'Richmond upon Thames', 'Rochdale', 'Rutland', 'Salford', 'Sandwell', 'Sefton', 'Sheffield', 'Shropshire', 'Slough', 'Solihull', 'Somerset', 'South Gloucestershire', 'South Tyneside', 'Southampton', 'Southend-on-Sea', 'Staffordshire', 'Stockport', 'Stoke-on-Trent', 'Suffolk', 'Sunderland', 'Surrey', 'Sussex Occidental', 'Sussex Oriental', 'Swindon', 'Tameside', 'Telford & Wrekin', 'Thurrock', 'Torbay', 'Tower Hamlets', 'Trafford', 'Wakefield', 'Walsall', 'Waltham Forest', 'Warrington', 'Warwickshire', 'West Berkshire', 'Westminster', 'Wigan', 'Wiltshire', 'Windsor and Maidenhead', 'Wokingham', 'Wolverhampton', 'Worcestershire', 'York', 'Yorkshire del Este', 'Yorkshire del Norte', 'de Londres', 'municipio de Southwark']::text[]),
  ('GBR-02', 'GBR', 'GBR', 'Escocia', array['Aberdeen', 'Aberdeenshire', 'Angus', 'Argyll and Bute', 'Clackmannanshire', 'Dumfries and Galloway', 'Dundee', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian', 'East Renfrewshire', 'Edimburgo', 'Falkirk', 'Fife', 'Glasgow', 'Highland', 'Inverclyde', 'Islas Hébridas Exteriores', 'Islas Shetland', 'Midlothian', 'Moray', 'North Ayrshire', 'North Lanarkshire', 'Orcadas', 'Perth and Kinross', 'Renfrewshire', 'Scottish Borders', 'South Ayrshire', 'South Lanarkshire', 'Stirling', 'West Dunbartonshire', 'West Lothian']::text[]),
  ('GBR-03', 'GBR', 'GBR', 'Gales', array['Anglesey', 'Blaenau Gwent', 'Bridgend', 'Caerphilly', 'Cardiff', 'Carmarthenshire', 'Ceredigion', 'Conwy', 'Denbighshire', 'Flintshire', 'Gwynedd', 'Merthyr Tydfil', 'Monmouthshire', 'Neath-Port Talbot', 'Newport', 'Pembrokeshire', 'Powys', 'Rhondda Cynon Taff', 'Swansea', 'Torfaen', 'Vale of Glamorgan', 'Wrexham']::text[]),
  ('GBR-04', 'GBR', 'GBR', 'Irlanda del Norte', array['Antrim', 'Ards', 'Armagh', 'Ballymena', 'Ballymoney', 'Banbridge', 'Belfast', 'Carrickfergus', 'Castlereagh', 'Coleraine', 'Craigavon', 'Derry', 'Down', 'Dungannon', 'Fermanagh', 'Larne', 'Limavady', 'Lisburn', 'Magherafelt', 'Mid Ulster', 'Moyle', 'Newry y Mourne', 'Newtownabbey', 'North Down', 'Omagh', 'Strabane']::text[]),
  ('ITA-01', 'ITA', 'ITA', 'Lombardía y Piamonte', array['Alessandria', 'Aosta', 'Asti', 'Biella', 'Brescia', 'Bérgamo', 'Como', 'Cremona', 'Cuneo', 'Imperia', 'La Spezia', 'Lecco', 'Liguria', 'Lodi', 'Mantua', 'Milán', 'Monza y Brianza', 'Novara', 'Pavía', 'Savona', 'Sondrio', 'Turín', 'Varese', 'Verbano-Cusio-Ossola', 'Vercelli']::text[]),
  ('ITA-02', 'ITA', 'ITA', 'Véneto y Emilia', array['Belluno', 'Bolonia', 'Ferrara', 'Forlì-Cesena', 'Gorizia', 'Módena', 'Padua', 'Parma', 'Piacenza', 'Pordenone', 'Reggio Emilia', 'Rovigo', 'Rávena', 'Rímini', 'Trentino', 'Trentino-Alto Adigio', 'Treviso', 'Trieste', 'Udine', 'Venecia', 'Verona', 'Vicenza']::text[]),
  ('ITA-03', 'ITA', 'ITA', 'Toscana y Lacio', array['Ancona', 'Arezzo', 'Ascoli Piceno', 'Fermo', 'Florencia', 'Frosinone', 'Grosseto', 'Latina', 'Livorno', 'Lucca', 'Macerata', 'Massa y Carrara', 'Perugia', 'Pesaro y Urbino', 'Pisa', 'Pistoia', 'Prato', 'Rieti', 'Roma', 'Siena', 'Terni', 'Viterbo']::text[]),
  ('ITA-04', 'ITA', 'ITA', 'Mezzogiorno', array['Avellino', 'Bari', 'Barletta-Andria-Trani', 'Benevento', 'Brindisi', 'Campobasso', 'Caserta', 'Catanzaro', 'Chieti', 'Cosenza', 'Crotona', 'Foggia', 'Isernia', 'L''Aquila', 'Lecce', 'Matera', 'Nápoles', 'Pescara', 'Potenza', 'Reggio Calabria', 'Salerno', 'Tarento', 'Teramo', 'Vibo Valentia']::text[]),
  ('ITA-05', 'ITA', 'ITA', 'Sicilia y Cerdeña', array['Agrigento', 'Cagliari', 'Caltanissetta', 'Carbonia-Iglesias', 'Catania', 'Enna', 'Medio Campidano', 'Mesina', 'Nuoro', 'Ogliastra', 'Olbia-Tempio', 'Oristán', 'Palermo', 'Ragusa', 'Sassari', 'Siracusa', 'Trapani']::text[]),
  ('MEX-01', 'MEX', 'MEX', 'Sonora y las Californias', array['Baja California', 'Baja California Sur', 'Sinaloa', 'Sonora']::text[]),
  ('MEX-02', 'MEX', 'MEX', 'Chihuahua y Durango', array['Chihuahua', 'Durango']::text[]),
  ('MEX-03', 'MEX', 'MEX', 'Sierra Madre Oriental', array['Coahuila de Zaragoza', 'Nuevo León', 'San Luis Potosí', 'Tamaulipas']::text[]),
  ('MEX-04', 'MEX', 'MEX', 'Jalisco y Michoacán', array['Aguascalientes', 'Colima', 'Jalisco', 'Michoacán', 'Nayarit', 'Zacatecas']::text[]),
  ('MEX-05', 'MEX', 'MEX', 'Valle de México y el Bajío', array['Estado de México', 'Guanajuato', 'Hidalgo', 'Morelos', 'México', 'Puebla', 'Querétaro', 'Tlaxcala']::text[]),
  ('MEX-06', 'MEX', 'MEX', 'Oaxaca y Chiapas', array['Chiapas', 'Guerrero', 'Oaxaca']::text[]),
  ('MEX-07', 'MEX', 'MEX', 'Yucatán y el Golfo', array['Campeche', 'Estado de Veracruz', 'Quintana Roo', 'Tabasco', 'Yucatán']::text[]),
  ('PRT-01', 'PRT', 'PRT', 'Portugal Continental', array['Aveiro', 'Beja', 'Braga', 'Braganza', 'Castelo Branco', 'Coímbra', 'Faro', 'Guarda', 'Leiría', 'Lisboa', 'Oporto', 'Portalegre', 'Santarém', 'Setúbal', 'Viana do Castelo', 'Vila Real', 'Viseu', 'Évora']::text[]),
  ('PRT-02', 'PRT', 'PRT', 'Azores', array['Azores']::text[]),
  ('PRT-03', 'PRT', 'PRT', 'Madeira', array['Madeira']::text[]),
  ('PRY-01', 'PRY', 'PRY', 'Chaco Paraguayo', array['Alto Paraguay', 'Boquerón', 'Presidente Hayes']::text[]),
  ('PRY-02', 'PRY', 'PRY', 'Alto Paraná y Amambay', array['Alto Paraná', 'Amambay', 'Caaguazú', 'Canindeyú', 'Concepción', 'San Pedro']::text[]),
  ('PRY-03', 'PRY', 'PRY', 'Asunción e Itapúa', array['Asunción', 'Caazapá', 'Central', 'Cordillera', 'Guairá', 'Itapúa', 'Misiones', 'Paraguarí', 'Ñeembucú']::text[]),
  ('USA-01', 'USA', 'USA', 'Nueva Inglaterra', array['Connecticut', 'Maine', 'Massachusetts', 'Nuevo Hampshire', 'Rhode Island', 'Vermont']::text[]),
  ('USA-02', 'USA', 'USA', 'Atlántico Medio', array['Nueva Jersey', 'Nueva York', 'Pensilvania']::text[]),
  ('USA-03', 'USA', 'USA', 'Grandes Lagos', array['Illinois', 'Indiana', 'Míchigan', 'Ohio', 'Wisconsin']::text[]),
  ('USA-04', 'USA', 'USA', 'Grandes Llanuras', array['Dakota del Norte', 'Dakota del Sur', 'Iowa', 'Kansas', 'Minnesota', 'Misuri', 'Nebraska']::text[]),
  ('USA-05', 'USA', 'USA', 'Carolinas y Florida', array['Carolina del Norte', 'Carolina del Sur', 'Delaware', 'Florida', 'Georgia', 'Maryland', 'Virginia', 'Virginia Occidental', 'Washington D. C.']::text[]),
  ('USA-06', 'USA', 'USA', 'Tennessee y Misisipi', array['Alabama', 'Kentucky', 'Misisipi', 'Tennessee']::text[]),
  ('USA-07', 'USA', 'USA', 'Texas y Luisiana', array['Arkansas', 'Luisiana', 'Oklahoma', 'Texas']::text[]),
  ('USA-08', 'USA', 'USA', 'Montañas Rocosas', array['Arizona', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'Nuevo México', 'Utah', 'Wyoming']::text[]),
  ('USA-09', 'USA', 'USA', 'Pacífico y Alaska', array['Alaska', 'California', 'Hawái', 'Oregón', 'Washington']::text[]);
